### ISSUE TITLE
FPC issues

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/yasox#11]
Hello just to share this nice snippet code provided by Jason about why FreePascal 64 bit not fails when an arithmetic overflow occurs using Cardinal. In Delphi it ocurr.

Jason message:

> C:\Projects\yasox>type test.pas
```
{$APPTYPE CONSOLE}
{$R+}
{$Q+}
program test;
var i1,i2:Cardinal;
begin
  i1 := 1048576;
  i2 := i1 * i1 div 1024;
  writeln(i2);
end.
```
> 
> C:\Projects\yasox>for %j in (fpc32 fpc64 delphi64 delphi32) do %j
> 
> C:\Projects\yasox>fpc32
> Runtime error 215 at $00401579
>   $00401579
> 
> 
> C:\Projects\yasox>fpc64
> 1073741824
> 
> C:\Projects\yasox>delphi64
> Runtime error 215 at 000000000040E20C
> 
> C:\Projects\yasox>delphi32
> Runtime error 215 at 0040A113
> 
> FPC didn't generate an error because the calculation succeeds.

Me: > Why FPC 64 version not fail?

Jason:

> It uses 64-bit instructions, Delphi uses 32-bit.
> 
> FPC:
> 
>         mov          edx,000100000
>         mov          rax,rdx
>         mul          rdx
> 
> Delphi:
> 
>         mov          d,[0004171E0],000100000
>         mov          eax,[0004171E0]
>         mul          d,[0004171E0]
> 

Thus, really worries me that FPC 64 bit produces code that does not have the same behaviour as Delphi 10.
Maybe remove the support for FPC?

Carlos

**Comment by adoxa** [comment]
Why not go the other way: Delphi does not have the same behaviour as FPC, maybe remove support for Delphi? This is a non-issue.
